export const AUTH_START = 'AUTH_START';
export const AUTH_PRE_SUCCESS = 'AUTH_PRE_SUCCESS';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const GUEST_INFO = 'GUEST_INFO';
export const GUARDIAN_FORM = 'GUARDIAN_FORM';
export const STUDENT_FORM = 'STUDENT_FORM';
export const DECLARATION_FORM = 'DECLARATION_FORM';
export const UPDATE_IMAGES = 'UPDATE_IMAGES';
export const RESET_VALUES_ON_DEFAULT = 'RESET_VALUES_ON_DEFAULT';

export const SUBMIT_ATTEMPT = "SUBMIT_ATTEMPT";
export const SUBMIT_NETWORK_FAIL = "SUBMIT_NETWORK_FAIL";
export const SUBMIT_INVALID_FAIL = "SUBMIT_INVALID_FAIL";
export const SUBMIT_SUCCESS = "SUBMIT_SUCCESS";

